WeatherAlert:
  required:
    - id
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/dataModel.Alert/master/alert-schema.yaml#/AlertCommons
  type: object
  description: A harmonised description of a Weather Alert
  properties: 
    subCategory: 
      type: string
      anyOf:
        - $ref: 'https://smart-data-models.github.io/dataModel.Weather/weather-schema.yaml#/WeatherAlertCategories'
