--- 
components: 
  schemas: 
    WeatherForecast: 
      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Weather/master/WeatherForecast/schema.yaml#/WeatherForecast"
info: 
  description: |
    This entity contains a harmonised description of a Weather Forecast. This entity
    is primarily associated with the vertical segments of the environment and
    agriculture but is applicable to many different applications.
    
    This data model has been developed in cooperation with mobile operators and the
    [GSMA](https://www.gsma.com/iot/iot-big-data/).
    
    You can see a description of weather forecast parameters provided by AEMET (in
    Spanish) [here](http://www.aemet.es/es/eltiempo/prediccion/municipios/ayuda)
  title: WeatherForecast
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - WeatherForecast
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Weather/master/WeatherForecast/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Weather/master/WeatherForecast/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
